"use client";

import Navbar from "./components/Navbar/page";
import SideBar from "./components/SideBar/page";
import "./globals.css";
import ReduxProvider from "./storeProvider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative antialiased`}>
        {/* <Provider store={store}> */}
        <ReduxProvider>
          <div className="flex w-full">
            <SideBar />
            <div className="block w-full">
              <Navbar />
              {children}
            </div>
          </div>
        </ReduxProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
