"use client";

import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/Navbar/page";
import SideBar from "./components/SideBar/page";
import "./globals.css";
import ReduxProvider from "./storeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Provider store={store}> */}
        <ReduxProvider>
          <div className="flex w-full">
            <SideBar />
            <div className="block w-full">
              <Navbar />
              {children}
            </div>
          </div>
        </ReduxProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
